// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func TodoFilters() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"px-4 pb-3 flex gap-1.5 text-xs\"><button @click=\"filter = 'all'\" :class=\"filter === 'all'\r\n\t\t\t\t? 'bg-amber-400 text-black border-amber-400'\r\n\t\t\t\t: 'text-white/60 border-white/10 hover:text-white hover:border-white/25'\" class=\"px-3 py-1.5 rounded-full border font-medium transition\">All</button> <button @click=\"filter = 'active'\" :class=\"filter === 'active'\r\n\t\t\t\t? 'bg-amber-400 text-black border-amber-400'\r\n\t\t\t\t: 'text-white/60 border-white/10 hover:text-white hover:border-white/25'\" class=\"px-3 py-1.5 rounded-full border font-medium transition\">Active</button> <button @click=\"filter = 'done'\" :class=\"filter === 'done'\r\n\t\t\t\t? 'bg-amber-400 text-black border-amber-400'\r\n\t\t\t\t: 'text-white/60 border-white/10 hover:text-white hover:border-white/25'\" class=\"px-3 py-1.5 rounded-full border font-medium transition\">Done</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
